# Generated by Django 3.0.2 on 2020-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bike_name', models.CharField(max_length=200)),
                ('Engine_Displacement', models.IntegerField()),
                ('max_power', models.IntegerField()),
                ('max_torque', models.IntegerField()),
                ('fuel', models.CharField(max_length=500)),
                ('gear', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
