# Generated by Django 3.0.2 on 2020-07-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0002_auto_20200726_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddetails',
            old_name='price',
            new_name='Price',
        ),
    ]
