# Generated by Django 3.0.2 on 2020-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0006_auto_20200726_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddetails',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
